name: Security Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Safety
        run: pip install safety

      - name: Run Safety Scan
        run: safety scan -r requirements.txt --full-report || true

      - name: Upload Safety Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: safety-scan-report
          path: safety.json
