name: Security Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Filter out Windows-specific dependencies
        run: grep -v "pywin32" requirements.txt > filtered_requirements.txt

      - name: Install dependencies
        run: pip install --upgrade --force-reinstall -r filtered_requirements.txt

      - name: Install Security Tools
        run: pip install safety pip-audit

      - name: Run Safety Scan
        run: |
          safety check -r filtered_requirements.txt --json > safety_report.json || true

      - name: Run pip-audit
        run: pip-audit --requirement filtered_requirements.txt --format=json > pip_audit_report.json || true

      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            safety_report.json
            pip_audit_report.json
